config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Matthew B. Gray
# Copyright 2019 Steven C Hartley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  resources :upgrades
  root to: "landing#index"

  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :landing
  resources :charges
  resources :themes
  resources :purchases
end

app/controllers/purchases_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
# Copyright 2019 AJ Esler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class PurchasesController < ApplicationController
  before_action :lookup_purchase, only: [:show, :update]

  # TODO(issue #24) list all members for people not logged in
  def index
    if user_signed_in?
      @my_purcahses = Purchase.joins(:user).where(users: {id: current_user})
      @my_purcahses = @my_purcahses.joins(:membership)
      @my_purcahses = @my_purcahses.includes(:charges).includes(active_claim: :detail)
    end

    if support_signed_in?
      @everyones_purchases = Purchase.includes(:user).joins(:membership)
    end
  end

  def new
    @purchase = Purchase.new
    @detail = Detail.new
    @offers = MembershipOffer.options
    @paperpubs = Detail::PAPERPUBS_OPTIONS.map { |o| [o.humanize, o] }
  end

  def show
    @detail = @purchase.active_claim.detail || Detail.new
    @my_offer = MembershipOffer.new(@purchase.membership)
    @outstanding_amount = AmountOwedForPurchase.new(@purchase).amount_owed
    @paperpubs = Detail::PAPERPUBS_OPTIONS.map { |o| [o.humanize, o] }
  end

  def create
    current_user.transaction do
      matching_offer = MembershipOffer.options.find do |offer|
        offer.to_s == params[:offer]
      end

      # TODO nicer errors
      raise "Offer not available to user" if !matching_offer.present?

      purchase_service = PurchaseMembership.new(matching_offer.membership, customer: current_user)
      new_purchase = purchase_service.call

      # TODO nicer errors
      raise "Failed to purchase membership" if !new_purchase.present?

      detail = Detail.new(params.require(:detail).permit(Detail::PERMITTED_PARAMS))
      detail.claim = new_purchase.active_claim

      # TODO nicer errors
      detail.save!

      flash[:notice] = "Congratulations member ##{new_purchase.membership_number}! You've just reserved a #{matching_offer.membership} membership"
      if new_purchase.membership.price.zero?
        redirect_to purchases_path
      else
        redirect_to new_charge_path(purchaseId: new_purchase.id)
      end
    end
  end

  def update
    current_user.transaction do
      current_details = @purchase.active_claim.detail
      submitted_values = params.require(:detail).permit(Detail::PERMITTED_PARAMS)
      if current_details.update(submitted_values)
        flash[:notice] = "Your details have been saved against Member ##{@purchase.membership_number}"
        redirect_to purchases_path
      else
        flash[:error] = current_details.errors.full_messages.to_sentence
        redirect_to purchase_path(@purchase)
      end
    end
  end
end

app/helpers/purchases_helper.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module PurchasesHelper
  def card_classes(purchase)
    if purchase.paid?
      "card"
    else
      "card text-white bg-dark border-light"
    end
  end
end

app/views/purchases/_detail_form.html.erb
<%#
  Copyright 2018 Rosanna Gray
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<%= form_for(@purchase) do |purchase_form| %>
  <%= fields_for(@detail) do |detail_form| %>
    <p>
      For more information about how we handle and use your personal information, please read our
      <a href="https://conzealand.nz/privacy-policy/" target="_blank">Privacy Policy</a> and our
      <a href="https://conzealand.nz/about-conzealand/policies-and-expectations/" target="_blank">Terms of Service</a>.
    </p>

    <fieldset class="l-v-spacing">
      <% if !(@purchase.present? && @purchase.persisted?) %>
        <legend>Membership Details</legend>

        <div class="form-group">
          <label for="offer">Membership type</span></label>
          <%= select_tag(:offer, options_for_select(@offers, @my_offer), class: "form-control", id: "membership_type") %>
        </div>
      <% end %>

      <fieldset class="l-v-spacing">
        <div class="row">
          <div class="col-12 col-md-2">
            <div class="form-group">
              <label for="title">Title</label>
              <%= detail_form.text_field(:title, class: "form-control", id: "title") %>
            </div>
          </div>

          <div class="col-12 col-md-5">
            <div class="form-group">
              <label for="first_name">First Name (required)</label>
              <%= detail_form.text_field(:first_name, required: true, class: "form-control", id: "first_name") %>
            </div>
          </div>

          <div class="col-12 col-md-5">
            <div class="form-group">
              <label for="last_name">Last Name (required)</label>
              <%= detail_form.text_field(:last_name, required: true, class: "form-control", id: "last_name") %>
            </div>
          </div>
        </div>

        <p class="form-note form-note-m-group">
          This is the name that appears on your official ID. We will need to check your ID at registration.
        </p>
      </fieldset>

      <fieldset class="l-v-spacing">
        <div class="row">
          <div class="col-12 col-md-6">
            <div class="form-group">
              <label for="preferred_first_name">Public First Name</span></label>
              <%= detail_form.text_field(:preferred_first_name, class: "form-control", id: "preferred_first_name") %>
            </div>
          </div>
          <div class="col-12 col-md-6">
            <div class="form-group">
              <label for="preferred_last_name">Public Last Name</label>
              <%= detail_form.text_field(:preferred_last_name, class: "form-control", id: "preferred_last_name") %>
            </div>
          </div>
        </div>
        <p class="form-note form-note-m-group">
          This is the name you would like to be addressed by.
          If it is left blank, you will be addressed by your legal name.
        </p>
      </fieldset>

      <fieldset class="l-v-spacing">
        <div class="row">
          <div class="col-12 col-md-6">
            <div class="form-group">
              <label for="badge_title">Badge Name</label>
              <%= detail_form.text_field(:badge_title, class: "form-control", id: "badge_title") %>
            </div>
          </div>
          <div class="col-12 col-md-6">
            <div class="form-group">
              <label for="badge_subtitle">Badge Subtitle</label>
              <%= detail_form.text_field(:badge_subtitle, class: "form-control", id: "badge_subtitle") %>
            </div>
          </div>
        </div>
        <p class="form-note form-note-m-group">
          This is the text we will print on your badge. It will default to Your preferred name and City and
          Country from your address. Both fields are modifiable.
        </p>
        <p class="form-note form-note-m-group">
          Please note that we reserve the right to reject text that falls outside our code of conduct.
        </p>
      </fieldset>

      <fieldset class="l-v-spacing">
        <div class="form-options">
          <%= detail_form.check_box(:share_with_future_worldcons, class: "form-control form-control-m-checkbox", id: "share_with_future_worldcons") %>
          <label for="share_with_future_worldcons">Share membership details with future worldcons?</label>
        </div>

        <p class="form-note form-note-m-group">
          Sharing your information with future Worldcons gives you the Hugo nominating rights for Worldcons other than
          2020 that come with your membership. If you answer no, you will not be able to exercise those rights.
        </p>

        <div class="form-options">
          <%= detail_form.check_box(:show_in_listings, class: "form-control form-control-m-checkbox", id: "show_in_listings") %>
          <label for="show_in_listings">List name on the CoNZealand website and in published directories?</label>
        </div>

        <p class="form-note form-note-m-group">
          SFCONZ and Worldcon 78 want to list your information on our websites.
        </p>
      </fieldset>
    </fieldset>

    <fieldset class="l-v-spacing">
      <legend>Address and Contact Information</legend>
      <p class="form-note form-note-m-group">
        Where do you get your postal mail? This should match your credit card address, if you use one.
      </p>

      <div class="form-group">
        <label for="address_line_1">Address Line 1 (required)</label>
        <%= detail_form.text_field(:address_line_1, required: true, class: "form-control", id: "address_line_1") %>
      </div>

      <div class="form-group">
        <label for="address_line_2">Address Line 2</label>
        <%= detail_form.text_field(:address_line_2, class: "form-control", id: "address_line_2") %>
      </div>

      <div class="form-group">
        <label for="city">City</label>
        <%= detail_form.text_field(:city, class: "form-control", id: "city") %>
      </div>

      <fieldset>
        <div class="row">
          <div class="col-12 col-md-6">
            <div class="form-group">
              <div class="form-group">
                <label for="province">State / Province / Region</label>
                <%= detail_form.text_field(:province, class: "form-control", id: "province") %>
              </div>
            </div>
          </div>

          <div class="col-12 col-md-6">
            <div class="form-group">
              <div class="form-group">
                <label for="postal">Post code</label>
                <%= detail_form.text_field(:postal, class: "form-control", id: "postal") %>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="country">Country (required)</label>
          <%= detail_form.text_field(:country, required: true, class: "form-control", id: "country") %>
        </div>
      </fieldset>

      <div class="form-group">
        <label for="publication_format">Paper pubs format</label>
        <%= detail_form.select(:publication_format, @paperpubs, {}, {
          class: "form-control",
          id: "publication_format",
        }) %>
      </div>

      <p class="form-note form-note-m-group">
        Our primary means of communication are electronic, in particular our registration system. Opting out of
        electronic publications does not mean that you will receive zero emails from us. It does mean that we
        will not attempt to send progress reports, etc., to your email address.
      </p>
    </fieldset>

    <fieldset class="l-v-spacing">
      <legend>Additional Options</legend>
      <p class="form-note form-note-m-group">
        This is how we know if you want to be contacted about specific things. We ask these questions to help us
        give you the experience you are after.
      </p>

      <div class="form-options">
        <%= detail_form.check_box(:interest_volunteering, class: "form-control form-control-m-checkbox", id: "interest_volunteering") %>
        <label for="interest_volunteering">I am interested in volunteering before or at the convention</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_accessibility_services, class: "form-control form-control-m-checkbox", id: "interest_accessibility_services") %>
        <label for="interest_accessibility_services">I would like information on disability or accessibility services at CoNZealand</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_being_on_program, class: "form-control form-control-m-checkbox", id: "interest_being_on_program") %>
        <label for="interest_being_on_program">I am interested in being a program participant</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_dealers, class: "form-control form-control-m-checkbox", id: "interest_dealers") %>
        <label for="interest_dealers">I am interested in vending in the Dealers Room</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_selling_at_art_show, class: "form-control form-control-m-checkbox", id: "interest_selling_at_art_show") %>
        <label for="interest_selling_at_art_show">I am interested in selling my art in the art show</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_exhibiting, class: "form-control form-control-m-checkbox", id: "interest_exhibiting") %>
        <label for="interest_exhibiting">I am interested in exhibiting at the convention</label>
      </div>

      <div class="form-options">
        <%= detail_form.check_box(:interest_performing, class: "form-control form-control-m-checkbox", id: "interest_performing") %>
        <label for="interest_performing">I am interested in performing at the convention</label>
      </div>
    </fieldset>

    <div class="l-v-spacing-both">
      <div class="form-group">
        <input type="submit" value="<%= detail_form_submit_text(@purchase) %>" class="btn btn-m-full-width">
      </div>

      <p>
        This purchase will show as being from 'CoNZealand'. We are based in New Zealand, and use Stripe as our
        payment processor.
      </p>

      <p>We do not store your credit card information.</p>
    </div>
  <% end %>
<% end %>

app/views/purchases/_sign_in_notice.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<p>
  You are currently signed out, please Login or Create an Account to view and puchase your memberships.
</p>
<%= render template: "/user_tokens/new" %>

app/views/purchases/index.html.erb
<%#
  Copyright 2019 Matthew B. Gray
  Copyright 2019 AJ Esler

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<h1>Review Memberships</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <% if !user_signed_in? %>
          <%= render "sign_in_notice" %>
        <% else %>
          <h2>
            My Memberships (<%= current_user.email %>)
          </h2>
          <p>You have <%= @my_purcahses.count %> memberships</p>

          <div class="card-columns">
            <% @my_purcahses.find_each(batch_size: 10) do |purchase| %>
              <div class="<%= card_classes(purchase) %>">
                <div class="card-body">
                  <h5 class="card-title">
                    #<%= purchase.membership_number %>

                    <% if detail = purchase.active_claim.detail %>
                      <%= detail %>
                    <% end %>
                  </h5>

                  <p class="card-text">
                    <%= purchase.membership %> Membership
                  </p>

                  <% if purchase.paid? %>
                    <% UpgradeOffer.from(purchase.membership).each do |offer| %>
                      <p>
                        <%= upgrade_link(purchase, offer: offer) %><br>
                        <em><%= offer.link_description %></em>
                      </p>
                    <% end %>
                  <% else %>
                    <p>Reserved, but not fully paid</p>
                    <p><%= link_to "Make a payment", new_charge_url(purchaseId: purchase.id) %></p>
                  <% end %>

                  <p><%= link_to("Review or update details", purchase_path(purchase)) %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<% if @everyones_purchases.present? %>
  <section class="l-section">
    <div class="row">
      <div class="col-12 col-md-12">
        <div class="l-panel">
          <h2>Full Members List</h2>
          <p>
            This page is a kind of godmode. Be careful who you show this too, these details are private.
          </p>
          <table>
            <thead>
              <th>Membership Number</th>
              <th>Member Name</th>
              <th>Membership level</th>
            </thead>
            <%= @everyones_purchases.find_each(batch_size: 100) do |purchase| %>
              <tbody>
                <tr>
                  <td><%= purchase.membership_number %></td>
                  <td><%= link_to(purchase.active_claim.detail, purchase_path(purchase)) %></td>
                  <td><%= purchase.membership.name.humanize %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/purchases/new.html.erb
<%#
  Copyright 2018 Rosanna Gray
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<h1>Purchase Membership</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="l-panel">
        <% if !user_signed_in? %>
          <%= render "sign_in_notice" %>
        <% else %>
          <h2>Membership Details</h2>
          <%= render "detail_form" %>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-md-4">
      <div class="l-panel l-panel-m-membership-types">
        <h2>Attending Membership</h2>

        <p>
          An Attending Membership is for people who can attend the convention physically.
          There are a number of different types of Attending Memberships.
          Attending Memberships are all inclusive.
          You do not have to pay anything more for autographs, attendance to panels, dances and so on.
          Note that some external events that are affiliated with, but not organised by, CoNZealand may have extra fees.
        </p>

        <p>
          You will receive all our publications.
          This also comes with the right to nominate and vote in the Hugo Awards in 2020.
          You can also vote in Site Selection for the 2022 Worldcon.
        </p>

        <p>
          Note: Kid In Tow does NOT come with voting rights in the Hugo Awards or Site Selections.
        </p>

        <h2>Supporting Membership</h2>

        <p>
          A Supporting Membership is for people who cannot attend the convention physically.
          You will receive all our publications.
          This also comes with the right to nominate and vote in the Hugo Awards in 2020.
          You can also vote in Site Selection for the 2022 Worldcon.
        </p>

        <p>
          You can always upgrade your supporting membership to attending memberships, at the price difference at the
          time.
        </p>

        <h2>Membership Transfer</h2>

        <p>
          We are happy to fully transfer a membership to another person.
          The person wanting to transfer, and the person receiving the transfer need to contact us at
          <a href="email:registrations@conzealand.nz">registrations@conzealand.nz</a>
        </p>

        <p>
          The transfer is of all rights that go along with that membership. If any of those rights have been exhausted,
          eg. by nominating or voting in the Hugos, then those rights are not available anymore.
        </p>

        <p>
          If the transferer wants to then be a supporting member in order to get rights for Hugo nominations, voting
          and Site Selection, then they will need to take out a fresh supporting membership.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/purchases/show.html.erb
<%#
  Copyright 2018 Rosanna Gray
  Copyright 2019 Matthew B. Gray
  Copyright 2019 AJ Esler

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<h1>Review Membership</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <h2><%= @my_offer.membership %> membership #<%= @purchase.membership_number %></h2>
        <% if @purchase.paid? %>
          <span>This membership is paid for.</span>
        <% else %>
          <p>There is <%= number_to_currency(@outstanding_amount / 100) %> NZD outstanding for this membership</p>
          <%= link_to "Make a payment", new_charge_url(purchaseId: @purchase.id) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="l-panel">
        <h2>Review your details</h2>
        <%= render "detail_form" %>
      </div>
    </div>

    <div class="col-12 col-md-4">
      <div class="l-panel l-panel-m-membership-types">
        <h2>Attending Membership</h2>

        <p>
          An Attending Membership is for people who can attend the convention physically.
          There are a number of different types of Attending Memberships.
          Attending Memberships are all inclusive.
          You do not have to pay anything more for autographs, attendance to panels, dances and so on.
          Note that some external events that are affiliated with, but not organised by, CoNZealand may have extra fees.
        </p>

        <p>
          You will receive all our publications.
          This also comes with the right to nominate and vote in the Hugo Awards in 2020.
          You can also vote in Site Selection for the 2022 Worldcon.
        </p>

        <p>
          Note: Kid In Tow does NOT come with voting rights in the Hugo Awards or Site Selections.
        </p>

        <h2>Supporting Membership</h2>

        <p>
          A Supporting Membership is for people who cannot attend the convention physically.
          You will receive all our publications.
          This also comes with the right to nominate and vote in the Hugo Awards in 2020.
          You can also vote in Site Selection for the 2022 Worldcon.
        </p>

        <p>
          You can always upgrade your supporting membership to attending memberships, at the price difference at the
          time.
        </p>

        <h2>Membership Transfer</h2>

        <p>
          We are happy to fully transfer a membership to another person.
          The person wanting to transfer, and the person receiving the transfer need to contact us at
          <a href="email:registrations@conzealand.nz">registrations@conzealand.nz</a>
        </p>

        <p>
          The transfer is of all rights that go along with that membership. If any of those rights have been exhausted,
          eg. by nominating or voting in the Hugos, then those rights are not available anymore.
        </p>

        <p>
          If the transferer wants to then be a supporting member in order to get rights for Hugo nominations, voting
          and Site Selection, then they will need to take out a fresh supporting membership.
        </p>
      </div>
    </div>
  </div>
</section>