config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Matthew B. Gray
# Copyright 2019 Steven C Hartley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  resources :upgrades
  root to: "landing#index"

  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :landing
  resources :charges
  resources :themes
  resources :purchases
end

app/models/charge.rb
# frozen_string_literal: true

# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Charge < ApplicationRecord
  STATE_FAILED = "failed"
  STATE_SUCCESSFUL = "successful"
  TRANSFER_STRIPE = "stripe"
  TRANSFER_CASH = "cash"

  belongs_to :user
  belongs_to :purchase

  validates :amount, presence: true
  validates :comment, presence: true
  validates :state, inclusion: {in: [STATE_FAILED, STATE_SUCCESSFUL]}
  validates :stripe_id, presence: true, if: :stripe_transfer?
  validates :transfer, presence: true, inclusion: {in: [TRANSFER_STRIPE, TRANSFER_CASH]}

  scope :stripe, ->() { where(transfer: TRANSFER_STRIPE) }
  scope :cash, ->() { where(transfer: TRANSFER_CASH) }
  scope :failed, ->() { where(state: STATE_FAILED) }
  scope :successful, ->() { where(state: STATE_SUCCESSFUL) }

  def stripe_transfer?
    transfer == TRANSFER_STRIPE
  end

  def successful?
    state == STATE_SUCCESSFUL
  end
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Test cards are here: https://stripe.com/docs/testing
class ChargesController < ApplicationController
  def index
  end

  def new
    @purchase = current_user.purchases.find(params.require(:purchaseId))

    if @purchase.paid?
      redirect_to purchases_path, notice: "You've paid for this #{@purchase.membership} membership"
      return
    end

    @membership = @purchase.membership
    @outstanding_amount = AmountOwedForPurchase.new(@purchase).amount_owed

    price_steps = PaymentAmountOptions.new(@outstanding_amount).amounts

    @price_options = price_steps.reverse.map do |price|
      [format_nzd(price), price]
    end
  end

  def create
    purchase = current_user.purchases.find(params[:purchaseId])
    charge_amount = params[:amount].to_i

    outstanding_before_charge = AmountOwedForPurchase.new(purchase).amount_owed

    allowed_charge_amounts = PaymentAmountOptions.new(outstanding_before_charge).amounts
    if !allowed_charge_amounts.include?(charge_amount)
      flash[:error] =  "Amount must be one of the provided payment amounts"
      redirect_to new_charge_path(purchaseId: purchase.id)
      return
    end

    service = ChargeCustomer.new(
      purchase,
      current_user,
      params[:stripeToken],
      outstanding_before_charge,
      charge_amount: charge_amount
    )

    charge_successful = service.call
    if !charge_successful
      flash[:error] = service.error_message
      redirect_to new_charge_path(purchaseId: purchase.id)
      return
    end

    if purchase.installment?
      PaymentMailer.installment(
        user: current_user,
        charge: service.charge,
        outstanding_amount: (outstanding_before_charge - charge_amount)
      ).deliver_later
    else
      PaymentMailer.paid(
        user: current_user,
        charge: service.charge,
      ).deliver_later
    end

    message = "Thank you for your #{format_nzd(charge_amount)} payment"
    (message += ". Your #{purchase.membership} membership has been paid for.") if purchase.paid?
    redirect_to purchases_path, notice: message
  end

  private

  def format_nzd(price)
    "#{helpers.number_to_currency(price / 100)} NZD"
  end
end

app/views/charges/index.html.erb
<%#
  Copyright 2019 Rosanna Gray
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<h1>New Membership</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="l-panel">
        <h2>Sign Up</h2>

        <p>
          <%= render "/shared/current_user_options" %>
        </p>

        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>

        <%= form_tag(charges_path, html: { class: "form form-m-membership", id: "membership-form" }) do %>
          <article>
            <label class="amount">
              <span>Amount: $5.00</span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Payment"
            data-amount="500"
            data-locale="auto"></script>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/charges/new.html.erb
<%
# Copyright 2019 AJ Esler
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
%>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="l-panel">
        <%= form_tag(charges_path, id: "purchase-form") do %>
          <article>
            <div id="error_explanation"></div>

            <p>You need to pay <%= number_to_currency(@outstanding_amount / 100) %> NZD to cover this membership.
            Please pay the full amount, or choose an installment from the list.</p>

            <label class="amount">
              <span>Amount:
                <%= select_tag(:amount, options_for_select(@price_options, selected: @outstanding_amount)) %>
              </span>
            </label>
          </article>

          <%= hidden_field_tag(:stripeToken) %>
          <%= hidden_field_tag(:stripeEmail) %>
          <%= hidden_field_tag(:purchaseId, @purchase.id) %>
          <div class="l-v-spacing-both">
            <div class="form-group">
              <%= submit_tag("Pay for #{@membership} membership", id: "purchase-button", class: "btn btn-m-full-width") %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  currency: 'NZD',
  name: 'CoNZealand',
  description: '<%= "CoNZealand #{@membership.name} membership" %>',
  email: '<%= current_user.email %>',
  token: function(token) {
    document.querySelector('input#stripeToken').value = token.id;
    document.querySelector('input#stripeEmail').value = token.email;

    document.querySelector('form#purchase-form').submit();
  }
});

document.querySelector('#purchase-button').addEventListener('click', function(e) {
  e.preventDefault();

  document.querySelector('#error_explanation').innerHtml = '';

  var amount = document.querySelector('select#amount').value;
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')

  amount = parseInt(amount);

  if (isNaN(amount)) {
    document.querySelector('#error_explanation').innerHtml = '<p>Please enter a valid amount in NZD ($).</p>';
  } else {
    handler.open({
      amount: amount
    })
  }
});

// Close Checkout on page navigation:
window.addEventListener('popstate', function() {
  handler.close();
});
</script>