config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Matthew B. Gray
# Copyright 2019 Steven C Hartley
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  resources :upgrades
  root to: "landing#index"

  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :landing
  resources :charges
  resources :themes
  resources :purchases
end

app/views/layouts/_alerts.html.erb
<%
# Copyright 2019 Matthew B. Gray
# Copyright 2019 AJ Esler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
%>

<% if notice.present? %>
  <p class="alert alert-primary alert-dismissible fade show" role="alert"><%= notice %></p>
<% end %>

<% if alert.present? %>
  <p class="alert alert-warning alert-dismissible fade show" role="alert">Alert: <%= alert %></p>
<% end %>

<% if flash[:error].present? %>
  <p class="alert alert-danger alert-dismissible fade show" role="alert"><%= flash[:error] %></p>
<% end %>

app/views/layouts/_menu.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<% if request.path != root_path %>
  <div class="<%= navigation_classes %> pointer"
    data-toggle="collapse"
    data-target="#navbarHeader"
  >
    <div class="container d-flex justify-content-between">
      <div
        class="navbar-brand d-flex align-items-center"
        aria-controls="navbarHeader"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <strong>Menu and Account Options</strong>
      </div>

      <button
        class="navbar-toggler collapsed"
        type="button"
        aria-controls="navbarHeader"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
<% else %>
  <div class="<%= navigation_classes %>">
    <div class="container d-flex justify-content-between">
      <div class="navbar-brand d-flex align-items-center">
        <strong>Welcome to the NEW Members Area</strong>
      </div>
    </div>
  </div>
<% end %>

<nav class="container <%= "collapse" if request.path != root_path %>" id="navbarHeader">
  <div class="row">
    <div class="col-sm-8 col-md-6 py-4">
      <ul class="list-unstyled">
        <li><%= link_to "Purchase Membership", new_purchase_path %></li>
        <li><%= link_to "Review Memberships", purchases_path %></li>
        <li>Suggest for our Programme (coming soon)</li>
        <li><a href="https://conzealand.nz/conzealand-needs">Volunteering</a></li>
        <li>Plan my trip(coming soon)</li>
        <li><a href="https://conzealand.nz">Back to CoNZealand homepage</a></li>
      </ul>
    </div>
    <div class="col-sm-4 offset-md-1 col-md-5 py-4">
      <% if user_signed_in? %>
        <h2 class="h4-like">Account actions</h2>
        <%= link_to("Logout #{current_user.email}", logout_user_tokens_path) %>
      <% else %>
        <h2 class="h4-like">Login or Create an Account</h2>
        <%= render template: "user_tokens/new" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
%>

<html>
  <head>
    <title>Conzealand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/conzealand.html.erb
<!doctype html>

<%#
  Copyright 2018 Rosanna Gray
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<html lang="en">
<head>
  <title>CoNZealand</title>
  <%= csrf_meta_tags %>

  <%#
    FIXME: Javascript in the header is bad for site performance

    Bootstrap re-initialises with JS in the body. Pages are loaded as a side-effect of turbolinks, and loading
    subsequent pages in over AJAX causes the menu to expand/contract quickly on the second page.
  %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Conzealand is a conference for science fiction enthusiasts.">
  <meta name="keywords" content="Conzealand, science fiction, conference, meet up, sci-fi" />
</head>
<body class="<%= "api-test-keys" if $stripe_test_keys %>">
  <%# TODO Style this to flash or something dramatic %>
  <% if support_signed_in? %>
    <div class="alert alert-danger show fixed-top" role="alert">
      NOTICE: You are logged in as support
      <%= button_to(
        "Logout of Support (#{current_support.email})",
        destroy_support_session_path,
        action: :delete, method: :delete, class: "button", style: "display: inline-block"
      ) %>
    </div>
  <% end %>

  <header>
    <div class="container l-v-spacing" role="banner">
      <a href="<%= root_path %>" class="logo">
        <%= image_tag "conzealand-logo.svg", alt: "CoNZealand", class: "img-responsive" %>
      </a>
    </div>

    <div class="container">
      <%= render "layouts/alerts" %>
    </div>

    <%= render "/layouts/menu" %>
  </header>

  <div class="l-main" role="main">
    <div class="container l-wrapper">
      <%= yield %>
    </div>
  </div>

  <footer role="contentinfo">
    <div class="container l-wrapper">
      <p>
        We outline how we use your personal information in our
        <a href="https://conzealand.nz/privacy-policy/">Privacy Policy</a>
      </p>
      <p>
        By using our members area, you are agreeing to follow our
        <a href="https://conzealand.nz/about-conzealand/policies-and-expectations/">Terms of Service</a>
      </p>
      <p>&copy; CoNZealand <%= Date.today.year %>. Contact <a href="mailto:registration@conzealand.nz">registration@conzealand.nz</a></p>
    </div>
  </footer>

  <% if $stripe_test_keys %>
    <script>
      (function initStyleToggler() {
        var button = $("<input>").attr({
          value: "Toggle Styles",
          title: "Stripe test keys present, this makes it clear you're in a staging environment",
          class: "btn",
          style: "position: relative; bottom: -2em; right: -2em;"
        });
        $("body").append(button);
        button.on("click", function() {
          $('body').toggleClass("api-test-keys");
        });
      })();
    </script>
  <% end%>
</body>
</html>